name: Deploy Static Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Files
        run: |
          echo "No build step needed - uploading raw files"
          echo "This avoids all third-party actions"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # GitHub Pages auto-deploys from this branch
          folder: .